import Head from "next/head";
import { Fragment } from "react";
import "../styles/globals.css";
import Layout from "../ui/layout/layout";
import { UserContextProvider } from "../store/user-context";

function MyApp({ Component, pageProps }) {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <UserContextProvider>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </UserContextProvider>
    </Fragment>
  );
}

export default MyApp;
